<?xml version = "1.0" encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE FAUST [
<!ELEMENT FAUST (ITEM)*>
<!ELEMENT ITEM (IDENT, BESTANDNR, BLATT?, STUECK?, COUVERTS?, BESTANDBILDNER?, TEILBESTANDBILDNER?, SIGNATUR?, SIGNATURALT?, SCHRIFT?, DATIERUNG?, DATIERUNGFEHL?, ORDNUNGSGRUPPE?, ZWUEBER?, KURZTITEL?, BEMERKUNG?, DRUCKORT?, ZWUEBER2?, VERWEIS?, UEBERLIEFERUNGSFORM?, DATUMBEILAGEN?, DABEI_VERMERK?)>
<!ATTLIST ITEM num CDATA #REQUIRED>
<!ELEMENT IDENT (#PCDATA)>
<!ELEMENT BESTANDNR (#PCDATA)>
<!ELEMENT BLATT (#PCDATA)>
<!ELEMENT STUECK (#PCDATA)>
<!ELEMENT COUVERTS (#PCDATA)>
<!ELEMENT BESTANDBILDNER (#PCDATA)>
<!ELEMENT TEILBESTANDBILDNER (#PCDATA)>
<!ELEMENT SIGNATUR (#PCDATA)>
<!ELEMENT SIGNATURALT (#PCDATA)>
<!ELEMENT SCHRIFT (#PCDATA)>
<!ELEMENT DATIERUNG (#PCDATA)>
<!ELEMENT DATIERUNGFEHL (#PCDATA)>
<!ELEMENT ORDNUNGSGRUPPE (#PCDATA)>
<!ELEMENT ZWUEBER (#PCDATA)>
<!ELEMENT KURZTITEL (#PCDATA)>
<!ELEMENT BEMERKUNG (#PCDATA)>
<!ELEMENT DRUCKORT (#PCDATA)>
<!ELEMENT ZWUEBER2 (#PCDATA)>
<!ELEMENT VERWEIS (#PCDATA)>
<!ELEMENT UEBERLIEFERUNGSFORM (#PCDATA)>
<!ELEMENT DATUMBEILAGEN (#PCDATA)>
<!ELEMENT DABEI_VERMERK (#PCDATA)>
]>
<FAUST>
   <ITEM num="1">
      <IDENT>390621</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>1</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,1,1</SIGNATUR>
      <SCHRIFT>egh</SCHRIFT>
      <DATIERUNG>Aug./Sept. 1798 (?)</DATIERUNG>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Faust. Erster Theil. Vorspiel auf dem Theater
Vers(e): 91-98
Wird vieles vor den Augen abgesponnen ...
WA: H; vgl. I 14,253; I 14,255
Konzept</KURZTITEL>
      <BEMERKUNG>zur Datierung vgl. Bohnenkamp, S.220</BEMERKUNG>
      <DRUCKORT>WA I 14, 7-16</DRUCKORT>
      <DABEI_VERMERK>Gedicht &quot;Wenn sichs in meinem Busen regt&quot;, = Paralipomenon Nr.6, WA I 5.2,358, Konzept egh, bei Bohnenkamp: P 5a, S. 219</DABEI_VERMERK>
   </ITEM>
   <ITEM num="2">
      <IDENT>391373</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>2</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,1,2</SIGNATUR>
      <SCHRIFT>Geist, egh</SCHRIFT>
      <DATIERUNG>1797/1798</DATIERUNG>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Faust. Erster Theil
Sammelblatt
WA: H; vgl. I 14,253 und I 14,255

Faust. Erster Theil. Prolog im Himmel
Vers(e): 331-353 (332-333 fehlt/fehlen)
Es ist mir gar nicht bange ...
Konzept
Text der Handschrift zu WA: I 14,23

Paralipomenon 2
Treten des Elements ...
Konzept
Text der Handschrift zu WA: I 14,287

Paralipomenon 18
Mit pathetischem Dünkel ...
Konzept
Text der Handschrift zu WA: I 14,293

Faust. Erster Theil. Prolog im Himmel
Paralipomenon 36
Vier Beine lieb ich mir ...
Konzept
Text der Handschrift zu WA: I 14,302

Faust. Erster Theil. Prolog im Himmel
Paralipomenon 37
Und selbst die allerkürzten Flügel ...
Konzept
Text der Handschrift zu WA: I 14,302

Paralipomenon 45
Was für ein hölzern Bild ...
Konzept
Text der Handschrift zu WA: I 14,303-304

Paralipomenon 46
Fiel vor mir hin ...
Konzept
Text der Handschrift zu WA: I 14,304

Paralipomenon 49
Siehst du er kommt ...
Konzept
Text der Handschrift zu WA: I 14,305

Paralipomenon 51
O wo ist der Genuß ...
Konzept
Text der Handschrift zu WA: I 14,311

Paralipomenon 70
Meph als Phisicien  Faust wie er regiren u nachsichtig ...
Konzept
Text der Handschrift zu WA: I 15.2,181

Paralipomenon 71
Und wenn du ganz was falsches ...
Konzept
Text der Handschrift zu WA: I 15.2,181

Paralipomenon 72
Mit diesen Menschen umzugehen ...
Konzept
Text der Handschrift zu WA: I 15.2,181

Paralipomenon 73
Wenn du sie nicht zum besten hast ...
Reinschrift
Text der Handschrift zu WA: I 15.2,182

Paralipomenon 74
Und was sie gerne wissen wollen ...
Konzept
Text der Handschrift zu WA: I 15.2,182</KURZTITEL>
      <BEMERKUNG>Lit.: Grumach, Ernst, Prolog und Epilog im Faustplan von 1797, in: Neue Folge des Jahrb. der Goethe-Gesellschaft, Band XIV/XV, S. 67 ff.</BEMERKUNG>
      <DRUCKORT>WA I 14, 17-23</DRUCKORT>
   </ITEM>
   <ITEM num="3">
      <IDENT>390489</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>1</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,1,3</SIGNATUR>
      <SCHRIFT>Kräuter</SCHRIFT>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Faust. Erster Theil
WA: oS; vgl. I 14,278
Umschlag (leer)
Titel der Handschrift: &quot;Faust (Aus) ein[ig]e Scene[n], am Ende [mehrentheils] von Goethes Hand.&quot; [ ] gestrichen
Signatur Kräuter: Eigen Poetisches 63.</KURZTITEL>
      <DABEI_VERMERK>Bemerkung &quot;Faust (Scene aus) zwischen Valentin und Gretchen, Goethe's Handschrift.&quot;, Kräuter [auf innerer Umschlagseite]</DABEI_VERMERK>
   </ITEM>
   <ITEM num="4">
      <IDENT>393795</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,1,4</SIGNATUR>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>entfällt</KURZTITEL>
      <VERWEIS>siehe Goethe Reproduktionen</VERWEIS>
   </ITEM>
   <ITEM num="5">
      <IDENT>391352</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>2</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,1,5</SIGNATUR>
      <SCHRIFT>Geist; egh</SCHRIFT>
      <DATIERUNG>1798</DATIERUNG>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Faust. Erster Theil
Szene &quot;Dom&quot;
Vers(e): 3776-3834
Wie anders, Gretchen, war dir's ...
WA: H; vgl. I 14,253; I 14,279
Reinschrift
Text der Handschrift zu WA: I 14,192-194</KURZTITEL>
      <BEMERKUNG>Datierung nach WA</BEMERKUNG>
   </ITEM>
   <ITEM num="6">
      <IDENT>393744</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,1,6</SIGNATUR>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>entfällt</KURZTITEL>
      <VERWEIS>siehe Goethe Reproduktionen</VERWEIS>
   </ITEM>
   <ITEM num="7">
      <IDENT>393832</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,1,7</SIGNATUR>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>entfällt</KURZTITEL>
      <VERWEIS>siehe Goethe Reproduktionen</VERWEIS>
   </ITEM>
   <ITEM num="8">
      <IDENT>391465</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>1</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,1,8:1</SIGNATUR>
      <SCHRIFT>egh</SCHRIFT>
      <DATIERUNG>1825 (?)</DATIERUNG>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Faust. Erster Theil. Walpurgisnachtstraum oder Oberons und Titanias goldne Hochzeit. Intermezzo
Vers(e): 4335-4338
Wie jeder doch die Beine ...
WA: H.1; vgl. I 14,253; I 14,281
Konzept
Text der Handschrift zu WA: I 14,220
auf Brief an Karl Wilhelm von Fritsch, 7.1.1826, WA IV 40,230, Konzept Schuchardt, Korrektur egh</KURZTITEL>
      <BEMERKUNG>Datierung nach WA</BEMERKUNG>
      <DRUCKORT>WA I 14, 213-223</DRUCKORT>
      <DABEI_VERMERK>Adresse egh &quot;Denen Königlich Großbrittanisch = Hannoverschen zum Hohen Cabinets Ministerio verordneten Herrn Geheimen Räthen Exzellenzen Hannover&quot; zu Brief vom 9.1.1826 vgl. Tagebucheintrag WA III 10,146,19-20</DABEI_VERMERK>
   </ITEM>
   <ITEM num="9">
      <IDENT>391353</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>1</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,1,8:2</SIGNATUR>
      <SCHRIFT>egh</SCHRIFT>
      <DATIERUNG>1826 (?)</DATIERUNG>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Faust. Erster Theil. Walpurgisnachtstraum oder Oberons und Titanias goldne Hochzeit. Intermezzo
Vers(e): 4335-4342
Wie jeder doch die Beine ...
WA: H.2; vgl. I 14,253; I 14,281
Konzept
Text der Handschrift zu WA: I 14,220
auf Brief von Müller, Friedrich von an unbekannten Empfänger &quot;... Euer Excellenz die Euch [...] Frankfurter...&quot;, Bru, Müller</KURZTITEL>
      <BEMERKUNG>Datierung nach Schöne, Albrecht, DKV-Ausgabe, Bd.7.2, S.366</BEMERKUNG>
      <DRUCKORT>WA I 14, 213-223</DRUCKORT>
   </ITEM>
   <ITEM num="10">
      <IDENT>391257</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>1</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,1,9:1</SIGNATUR>
      <SCHRIFT>Eckermann</SCHRIFT>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Weimarische Inscenirungsversuche. Zum Radziwillschen Faust. Monodrama.
WA: oS; vgl. I 14,314
Kapsel
Titel der Handschrift: &quot;Zu Faust. (Wahrscheinlich bei einer einstens beabsichtigten Bearbeitung für die Bühne.)&quot;
Signatur Kräuter: Eigen Poetisches 38.delta</KURZTITEL>
      <BEMERKUNG>enthielt 25/XVII,1,9:2</BEMERKUNG>
      <DRUCKORT>WA I 14, 314-321</DRUCKORT>
   </ITEM>
   <ITEM num="11">
      <IDENT>390352</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>2</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,1,9:2</SIGNATUR>
      <SCHRIFT>Wolff, Pius Alexander, egh</SCHRIFT>
      <DATIERUNG>Herbst 1812</DATIERUNG>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Weimarische Inscenirungsversuche. Zum Radziwillschen Faust. Monodrama.
WA: oS; vgl. I 14,314
Schema
Schema für eine Bühneneinrichtung</KURZTITEL>
      <BEMERKUNG>zur Datierung vgl. Bohnenkamp, S.248</BEMERKUNG>
      <DRUCKORT>WA I 14, 314-321</DRUCKORT>
   </ITEM>
   <ITEM num="12">
      <IDENT>390789</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>2</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,1,10:1</SIGNATUR>
      <SCHRIFT>egh</SCHRIFT>
      <DATIERUNG>1814 oder 1819 (?)</DATIERUNG>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Weimarische Inscenirungsversuche. Zum Radziwillschen Faust. Monodrama.
So mag es bey der Fratze ...
WA: oS; vgl. I 14,317-318
Reinschrift
Zwei Geisterchöre für die Paktszene
Titel der Handschrift: &quot;Zu Faust&quot;</KURZTITEL>
      <BEMERKUNG>zur Datierung vgl. Bohnenkamp, S. 261</BEMERKUNG>
      <DRUCKORT>WA I 14, 314-321</DRUCKORT>
   </ITEM>
   <ITEM num="13">
      <IDENT>390753</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>2</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,1,10:2</SIGNATUR>
      <SCHRIFT>Riemer</SCHRIFT>
      <DATIERUNG>bis zum 11.4.1814</DATIERUNG>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Weimarische Inscenirungsversuche. Zum Radziwillschen Faust. Monodrama.
Er kommt! Er kommt ...
WA: H.1; vgl. I 14,319
Reinschrift
Bearbeitung der Gartenhäuschenszene
Titel der Handschrift: &quot;Ein Gartenhäuschen.&quot;</KURZTITEL>
      <BEMERKUNG>zur Datierung vgl. Bohnenkamp, S. 259</BEMERKUNG>
      <DRUCKORT>WA I 14, 314-321</DRUCKORT>
   </ITEM>
   <ITEM num="14">
      <IDENT>390263</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>1</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,1,10:3</SIGNATUR>
      <SCHRIFT>Kräuter; egh</SCHRIFT>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Weimarische Inscenirungsversuche. Zum Radziwillschen Faust. Monodrama.
WA: -
Umschlag
Titel der Handschrift: &quot;Paralipomena&quot; [Kräuter], &quot;Zu Faust&quot; [egh]
Signatur Kräuter: Eigen Poetisches 38.epsilon</KURZTITEL>
      <DRUCKORT>WA I 14, 314-321</DRUCKORT>
   </ITEM>
   <ITEM num="15">
      <IDENT>390076</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>1</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,1,10:4</SIGNATUR>
      <SCHRIFT>egh</SCHRIFT>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Faust. Erster Theil
WA: -
Umschlag, links oben Zuordnungsvermerk mit Blei &quot;ad 24&quot;</KURZTITEL>
   </ITEM>
   <ITEM num="16">
      <IDENT>389781</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>1</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,1,10:5</SIGNATUR>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>leeres Blatt</KURZTITEL>
   </ITEM>
   <ITEM num="17">
      <IDENT>390583</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>9</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,1,11:1</SIGNATUR>
      <SCHRIFT>zS</SCHRIFT>
      <DATIERUNG>1815</DATIERUNG>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Weimarische Inscenirungsversuche. Zum Radziwillschen Faust. Monodrama.
WA: H; vgl. I 14,321
Titel der Handschrift: &quot;Faust's Monolog.&quot; [Kräuter]
Signatur Kräuter: Eigen Poetisches 64.

Vers(e): 354-517
Habe nun, ach! Philosophie ...
Reinschrift
Text der Handschrift zu WA: I 14,27-33

Vers(e): 614-629
Ich Ebenbild der Gottheit ...
Reinschrift
Text der Handschrift zu WA: I 14,37

Vers(e): 686-807
Doch warum heftet sich mein Blick ...
Reinschrift
Text der Handschrift zu WA: I 14,39-44

Hier soll ich bangen, ...
Reinschrift</KURZTITEL>
      <BEMERKUNG>= Folioheft, dazu A in H.2 (25/XVII,1,11:2)</BEMERKUNG>
      <DRUCKORT>WA I 14, 314-321</DRUCKORT>
   </ITEM>
   <ITEM num="18">
      <IDENT>390822</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>1</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,1,11:2</SIGNATUR>
      <SCHRIFT>John</SCHRIFT>
      <DATIERUNG>Mai 1815</DATIERUNG>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Weimarische Inscenirungsversuche. Zum Radziwillschen Faust. Monodrama.
Hier soll ich bangen ...
WA: H.2; vgl. I 14,321
Abschrift
Titel der Handschrift: &quot;Zum verkürzten Melodrama Faust. /: nach: 'Ins ungewiße Menschenloos.':/&quot;</KURZTITEL>
      <BEMERKUNG>dazu Reinschrift in H (25/XVII,1,11:1*d); zur Datierung vgl. Bohnenkamp, S. 263</BEMERKUNG>
      <DRUCKORT>WA I 14, 314-321</DRUCKORT>
   </ITEM>
   <ITEM num="19">
      <IDENT>390720</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>1</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,2,1</SIGNATUR>
      <SCHRIFT>egh</SCHRIFT>
      <DATIERUNG>1800 (?)</DATIERUNG>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Faust. Erster Theil
Paralipomenon I 
Ideales streben nach Einwircken ...
WA: oS; vgl. I 14,287
Konzept</KURZTITEL>
      <DABEI_VERMERK>Datierung &quot;11. April 1800&quot;, sS</DABEI_VERMERK>
   </ITEM>
   <ITEM num="20">
      <IDENT>390259</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>1</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,2,2</SIGNATUR>
      <SCHRIFT>egh</SCHRIFT>
      <DATIERUNG>Aug./Sept. 1798</DATIERUNG>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Faust. Erster Theil
WA: oS; vgl. I 14,288

Paralipomenon 3
Und wenn der Narr ...
Konzept
Text der Handschrift zu WA: I 14,288

Vers(e): 3-4
Paralipomenon 4
Und wer euch heut recht derb ...
Konzept
Zeile 3 und 4 von Nr 4
Text der Handschrift zu WA: I 14,288</KURZTITEL>
   </ITEM>
   <ITEM num="21">
      <IDENT>391357</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>1</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,2,3</SIGNATUR>
      <SCHRIFT>egh</SCHRIFT>
      <DATIERUNG>1798 (?)</DATIERUNG>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Faust. Erster Theil
Paralipomenon 4
Und wenn ihr scheltet ...
WA: oS; vgl. I 14,288
Konzept
Text der Handschrift zu WA: I 14,288</KURZTITEL>
   </ITEM>
   <ITEM num="22">
      <IDENT>389765</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>1</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,2,4</SIGNATUR>
      <SCHRIFT>egh</SCHRIFT>
      <DATIERUNG>Aug./Sept. 1798</DATIERUNG>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Faust. Erster Theil
Paralipomenon 5
Nur heute schränckt ...
WA: oS; vgl. I 14,288
Konzept
Text der Handschrift zu WA: I 14,288</KURZTITEL>
   </ITEM>
   <ITEM num="23">
      <IDENT>390900</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>1</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,2,5</SIGNATUR>
      <SCHRIFT>egh</SCHRIFT>
      <DATIERUNG>1797/1798 (?)</DATIERUNG>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Faust. Erster Theil
Paralipomenon 8
Und schleppe noch bey diesem ...
WA: oS; vgl. I 14,289
Konzept
Text der Handschrift zu WA: I 14,289</KURZTITEL>
      <BEMERKUNG>zur Datierung vgl. Bohnenkamp, S.132</BEMERKUNG>
      <DABEI_VERMERK>Numerierung &quot;ad 6.&quot; egh [Rötel, rechts, unter den Versen]</DABEI_VERMERK>
   </ITEM>
   <ITEM num="24">
      <IDENT>390186</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>1</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,2,6:1</SIGNATUR>
      <SCHRIFT>egh</SCHRIFT>
      <DATIERUNG>1797/1798 (?)</DATIERUNG>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Faust. Erster Theil
Sammelblatt
WA: oS; vgl. I 14,289

Paralipomenon 9
Wenn du von aussen ausgestattet ...
Konzept
Text der Handschrift zu WA: I 14,289

Paralipomenon 43
Was an dem Lumpenpack ...
Konzept
Text der Handschrift zu WA: I 14,303

Paralipomenon Par 62 (bei Par 62 aufgeführt)
er heißt sogar der große ...
Konzept
Text der Handschrift zu WA: I 14,313

Paralipomenon 62
Die Welt geht auseinander ...
= Vers 1329-1330 von Zahme Xenien. V.: &quot;Komm her! ...&quot;  WA I 3,325
Konzept
Text der Handschrift zu WA: I 14,313

Paralipomenon 64
Bedauren der traurig zugebrachten ...
Schema
Text der Handschrift zu WA: I 15.2,177</KURZTITEL>
      <DABEI_VERMERK>Numerierung &quot;12&quot; zS [oben rechts, Blei]</DABEI_VERMERK>
   </ITEM>
   <ITEM num="25">
      <IDENT>391360</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>1</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,2,6:2</SIGNATUR>
      <SCHRIFT>egh</SCHRIFT>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Faust. Erster Theil
Paralipomenon 9 (Andere Überlieferung zu Paralipomenon 9)
Wenn du von aussen ausgestattet ...
WA: -
Reinschrift</KURZTITEL>
      <BEMERKUNG>bei Bohnenkamp nur erwähnt auf S. 129 - Vermutung als Geschenkblatt vorgesehen</BEMERKUNG>
   </ITEM>
   <ITEM num="26">
      <IDENT>391362</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>2</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,2,7</SIGNATUR>
      <SCHRIFT>egh, Geist</SCHRIFT>
      <DATIERUNG>1797/1798 (?)</DATIERUNG>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Faust. Erster Theil
Sammelblatt
WA: H; vgl. I 14,253 und I 14,275
Titel der Handschrift: &quot;Faust.&quot; egh

Paralipomenon 10 (Teilüberlieferung zu Paralipomenon 10)
Und es verzeihen ...
Konzept
Text der Handschrift zu WA: I 14,290

Paralipomenon 10
Seht mir nur ab ...
Konzept
Text der Handschrift zu WA: I 14,289-290

Paralipomenon 19
Die Wahrheit zu ergründen ...
Konzept
Text der Handschrift zu WA: I 14,293

Paralipomenon 33
Wie man nach Norden ...
Konzept
Text der Handschrift zu WA: I 14,301

Paralipomenon 34
Leuchtende Finger des Meph. ...
Konzept
Text der Handschrift zu WA: I 14,301

Paralipomenon 35
Ihr Leben ist ein bloser ...
Konzept
Text der Handschrift zu WA: I 14,302

Paralipomenon 38
Bestünde nur die Weisheit ...
Konzept
Text der Handschrift zu WA: I 14,302

Paralipomenon 39 (andere Überlieferung zu Paralipomenon 39)
Ich wäre nicht so arm an Witz ...
Konzept
Text der Handschrift zu WA: I 14,302

Paralipomenon 44
Musick nur her ...
Konzept
Text der Handschrift zu WA: I 14,303

Faust. Zweiter Theil. Dritter Act
Paralipomenon 52
Die spindelförmigen Gestalten! ...
Konzept
Text der Handschrift zu WA: I 14,311

Paralipomenon 53
Fleisch dorrt wie Heu ...
Konzept
Text der Handschrift zu WA: I 14,311

Vers(e): 3149-3152
Die Guten Weiber sind doch übel dran ...
Konzept

Faust. Zweiter Theil. Aus dem Nachlaß. Epilog um 1800. Abkündigung
Paralipomenon 97 (andere Überlieferung zu Paralipomenon 97)
Das Leben ist ein episches Gedicht ...
Konzept
Text der Handschrift zu WA: I 15.2,188</KURZTITEL>
      <BEMERKUNG>Lit.: Grumach, Ernst: Aus Goethes Vorarbeiten zu den Helenaszenen, Neue Folge des Jahrbuchs der Goethe-Gesellschaft, Bd. XX, S.46 ff., nur Verse 7 und 8, in WA I 14,275 fehlerhaft als Par. Nr. 29 aufgeführt, in WA I 14,275 fehlerhaft als Pa</BEMERKUNG>
      <DRUCKORT>WA I 15.1, 177-244, WA I 15.1, 344-</DRUCKORT>
      <DABEI_VERMERK>Numerierung &quot;2/164/8/21&quot; egh, [oben rechts, Tinte]</DABEI_VERMERK>
   </ITEM>
   <ITEM num="27">
      <IDENT>391365</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>3</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,2,8</SIGNATUR>
      <SCHRIFT>egh</SCHRIFT>
      <DATIERUNG>April (?) 1801</DATIERUNG>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Faust. Erster Theil
Paralipomenon 11
Disputation. Halbchor ...
WA: oS; vgl. I 14,290-291
Schema
Text der Handschrift zu WA: I 14,290-291</KURZTITEL>
      <BEMERKUNG>mit einem Faden zusammengeheftete Blätter</BEMERKUNG>
      <DABEI_VERMERK>Konzept egh &quot;Ich erkl[äre] mich [in] dieser/ so Sache durch ein Bey[spiel]/ Genuß/ Resig[nation] Gewohn[heit]/ Streben&quot; zu Brief an unbekannten Empfänger vom 1.5.1801 WA IV 15,228,6-13; Tagebuchnotiz egh zum 29.4.1801 &quot;In Winckelweiden 3 1/2 Std&quot; vgl. WA III 3,12</DABEI_VERMERK>
   </ITEM>
   <ITEM num="28">
      <IDENT>390778</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>1</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,2,9</SIGNATUR>
      <SCHRIFT>egh</SCHRIFT>
      <DATIERUNG>1801 (?)</DATIERUNG>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Faust. Erster Theil
Paralipomenon 12
Lasst uns hinaus! ...
WA: oS; vgl. I 14,291-292
Konzept
Text der Handschrift zu WA: I 14,291-292</KURZTITEL>
   </ITEM>
   <ITEM num="29">
      <IDENT>389808</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>1</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,2,10</SIGNATUR>
      <SCHRIFT>Geist</SCHRIFT>
      <DATIERUNG>1797/1798 (?)</DATIERUNG>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Faust. Erster Theil
Paralipomenon 14
Zu suchen wo auf Erden ...
WA: oS; vgl. I 14,292
Konzept
Text der Handschrift zu WA: I 14,292</KURZTITEL>
   </ITEM>
   <ITEM num="30">
      <IDENT>389847</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>1</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,2,11</SIGNATUR>
      <SCHRIFT>egh</SCHRIFT>
      <DATIERUNG>April 1800 (?)</DATIERUNG>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Faust. Erster Theil
WA: oS; vgl. I 14,292

Paralipomenon 15
Das was uns trennt ...
Konzept
Text der Handschrift zu WA: I 14,292

Paralipomenon 16
Als Pudel als Gespenst ...
Konzept
Text der Handschrift zu WA: I 14,292

Paralipomenon 17
Wer spricht von Zweifeln ...
Konzept
Text der Handschrift zu WA: I 14,293</KURZTITEL>
   </ITEM>
   <ITEM num="31">
      <IDENT>390887</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>1</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,2,12</SIGNATUR>
      <SCHRIFT>egh</SCHRIFT>
      <DATIERUNG>1797/98 (?)</DATIERUNG>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Faust. Erster Theil
Sammelblatt
WA: oS; vgl. I 14,293

Paralipomenon 20
Und merck dir ein für allemal ...
Konzept
Text der Handschrift zu WA: I 14,293

Paralipomenon 41
Ein Mensch der von sich spricht ...
Konzept
Text der Handschrift zu WA: I 14,303

Paralipomenon 82 (andere Überlieferung zu Paralipomenon 82)
Das hat schon der Prophet ...
Konzept
Text der Handschrift zu WA: I 15.2,183

Paralipomenon Par 20 bzw. Par 5
Und Freude schwebt ...
Konzept
Text der Handschrift zu WA: I 14,293 bzw I 5.2,357</KURZTITEL>
      <BEMERKUNG>zur Datierung vgl. Bohnenkamp, S.197</BEMERKUNG>
   </ITEM>
   <ITEM num="32">
      <IDENT>390782</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>1</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,2,13</SIGNATUR>
      <SCHRIFT>egh</SCHRIFT>
      <DATIERUNG>zwischen 1773 und 1775</DATIERUNG>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Faust. Erster Theil
Sammelblatt
WA: oS; vgl. I 14,294

Paralipomenon 21
Was giebts Mephisto ...
Konzept
Text der Handschrift zu WA: I 14,294

Paralipomenon 6
Mich darf niemand auf's Gewissen ...
Konzept
Text der Handschrift zu WA: I 14,288

Paralipomenon 7
Mein Freund wenn je der Teufel ...
Konzept
Text der Handschrift zu WA: I 14,288</KURZTITEL>
      <BEMERKUNG>zur Datierung vgl. Bohnenkamp, S.104</BEMERKUNG>
   </ITEM>
   <ITEM num="33">
      <IDENT>390888</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>2</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,2,14</SIGNATUR>
      <SCHRIFT>egh</SCHRIFT>
      <DATIERUNG>1797 (?)</DATIERUNG>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Faust. Erster Theil
WA: oS; vgl. I 14,294

Paralipomenon 22
Faust Meph/ F. Umgekehrte Richtung ...
Schema
Text der Handschrift zu WA: I 14,294-295

Paralipomenon 24
Kleine Reichsst. Das anmuthige ...
Schema
Text der Handschrift zu WA: I 14,295

Paralipomenon 31
Aufmunterung zu Walp. Nacht ...
Schema
Text der Handschrift zu WA: I 14,301

Paralipomenon 48
Nach dem Intermezz ...
Schema
Text der Handschrift zu WA: I 14,305</KURZTITEL>
      <BEMERKUNG>zur Datierung vgl. Bohnenkamp, S.177</BEMERKUNG>
   </ITEM>
   <ITEM num="34">
      <IDENT>391368</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>1</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,2,15</SIGNATUR>
      <SCHRIFT>egh</SCHRIFT>
      <DATIERUNG>um 1800</DATIERUNG>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Faust. Erster Theil
Paralipomenon 25
Doppel-Scene Andreas Nacht ...
WA: oS; vgl. I 14,295
Schema
Text der Handschrift zu WA: I 14,295</KURZTITEL>
   </ITEM>
   <ITEM num="35">
      <IDENT>391369</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>1</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,2,16</SIGNATUR>
      <SCHRIFT>Geist</SCHRIFT>
      <DATIERUNG>1797/1798</DATIERUNG>
      <ORDNUNGSGRUPPE>Werke</ORDNUNGSGRUPPE>
      <ZWUEBER>Dramatische Werke</ZWUEBER>
      <KURZTITEL>Faust. Erster Theil
Paralipomenon 26
Der junge Herr ist freylich ...
WA: oS; vgl. I 14,295-296
Abschrift
Text der Handschrift zu WA: I 14,296</KURZTITEL>
      <BEMERKUNG>Erstdruck: Q, S.178</BEMERKUNG>
      <DABEI_VERMERK>Zuordnungsvermerk &quot;ad 16./ e&quot;, egh [oben, rechts, Blei und Tinte]</DABEI_VERMERK>
   </ITEM>
   <ITEM num="36">
      <IDENT>389816</IDENT>
      <BESTANDNR>25</BESTANDNR>
      <BLATT>1</BLATT>
      <BESTANDBILDNER>Goethe, Johann Wolfgang von / Werke</BESTANDBILDNER>
      <SIGNATUR>XVII,2,17</SIGNATUR>
      <SCHRIFT>egh</SCHRIFT>
      <DATIERUNG>1800(?), 1800/1801 (?)</DATIERUNG>